# Generated by Django 3.1.7 on 2021-04-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('Al', 'All'), ('Rd', 'Read')], default='Al', max_length=2)),
                ('role', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=128)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Middle', 'Middle'), ('High', 'High')], default='Middle', max_length=6)),
                ('tag', models.CharField(choices=[('Bug', 'Bug'), ('Improve', 'Improve'), ('Task', 'Task')], default='Bug', max_length=7)),
                ('status', models.CharField(choices=[('Todo', 'Todo'), ('Inprogress', 'Inprogress'), ('Finished', 'Finished')], default='Todo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('Back', 'Back'), ('Front', 'Front'), ('iOS', 'iOS'), ('Android', 'Android')], default='Back', max_length=7)),
            ],
        ),
    ]
