# Generated by Django 3.1.7 on 2021-03-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('AU', 'Author'), ('RE', 'Responsible'), ('CR', 'Creator')], default='AU', max_length=2),
        ),
    ]
