# Generated by Django 3.1.7 on 2021-04-16 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_auto_20210414_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('Al', 'All'), ('Rd', 'Read')], default='Rd', max_length=2),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assignee_user_id',
            field=models.ForeignKey(blank=True, default=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_author', to=settings.AUTH_USER_MODEL), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
