# Generated by Django 3.1.7 on 2021-04-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210416_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Back', 'Back'), ('Front', 'Front'), ('iOS', 'iOS'), ('Android', 'Android')], default='Back', max_length=7),
        ),
    ]
